# 1.2
university_variable = "TheUniversityOfManchesterFacultyofBiologyMedicineAndHealth"
sub_string_1 = university_variable[3:13]
sub_string_2 = university_variable[15:25]

print(sub_string_1 + ' ' + sub_string_2)


# 1.2
DNA_seq = """GCTGAGACTTCCTGGACGGGGGACAGGCTGTGGGGTTTCTCAGATAACTGGG
CCCCTGCGCTCAGGAGGCCTTCACCCTCTGCTCTGGGTAAAGTTCATTGGAACAGAAAGAAATGG
ATTTATCTGCTCTTCGCGTTGAAGAAGTACAAAATGTCATTAATGCTATGCAGAAAATCTTAGAG
TGTCCCATCTGTCTGGAGTTGATCAAGGAACCTGTCTCCACAAAGTGTGACCACATATTTTGCAA
ATTTTGCATGCTGAAACTTCTCAACCAGAAGAAAGGGCCTTCACAGTGTCCTTTATGTAAGAATG
ATATAACCAAAAGGAGCCTACAAGAAAGTACGAGATTTGAT"""
subDNA1 = DNA_seq[137:143]
subDNA2 = DNA_seq[274:280]

print(subDNA1 + subDNA2)